spring:
  cloud:
    gateway:
      routes:
        - id: coupon_route
          uri: lb://gulimall-coupon
          predicates:
          - Path=/api/gulimall_coupon/**
          filters:
          - RewritePath=/api/(?<segment>.*), /$\{segment}
        - id: member_route
          uri: lb://gulimall-member
          predicates:
          - Path=/api/gulimall_member/**
          filters:
          - RewritePath=/api/(?<segment>.*), /$\{segment}
        - id: order_route
          uri: lb://gulimall-order
          predicates:
          - Path=/api/gulimall_order/**
          filters:
          - RewritePath=/api/(?<segment>.*), /$\{segment}
        - id: product_route
          uri: lb://gulimall-product
          predicates:
          - Path=/api/gulimall_product/**
          filters:
          - RewritePath=/api/(?<segment>.*), /$\{segment}
        - id: ware_route
          uri: lb://gulimall-ware
          predicates:
          - Path=/api/gulimall_ware/**
          filters:
          - RewritePath=/api/(?<segment>.*), /$\{segment}
        - id: admin_route
          uri: lb://renren-fast
          predicates:
          - Path=/api/**
          filters:
          - RewritePath=/api/(?<segment>.*), /renren-fast/$\{segment}